unique_ids:
  assets:
    standard-page.html: AQRL72T57FSMYXFBQAJJLT2D6INQUTX2
    theme.css: PFCIZYNQ6UZ3LN67LRGEWELR7UMJMAUJ
  forms:
    Form1: 2P6GMMCYIG53ZYUYD7ETDBB5I2COPXUL
  modules: {}
  scripts: {}
  server_modules: {}
